spring:
  application:
    name: order-service
    
#server:
 # port: 8201

sp:
  user-service:
    users: "[{\"id\":7, \"username\":\"abc\",\"password\":\"123\"},{\"id\":8, \"username\":\"def\",\"password\":\"456\"},{\"id\":9, \"username\":\"ghi\",\"password\":\"789\"}]"

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
#启用feign ，ribbon重试和hystrix超时不设置，使用默认值      
feign:
  hystrix:
    enabled: true
#暴露监控断点 
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
 
---
spring:
  profiles: order1
 
server:
  port: 8201
 
---
spring:
  profiles: order2
 
server:
  port: 8202
